### ISSUE TITLE
Ugly home

### ISSUE THREAD

**Issue by StivenKN** [sena-proyectos/practicas-ctm#59]
![imagen](https://github.com/sena-proyectos/practicas-ctm/assets/80909795/7c38ec27-1781-4c42-ba6e-32198ea8b9eb)

**Comment by lorenqg** [comment]
Solucionado :)
<img width="960" alt="image" src="https://github.com/sena-proyectos/practicas-ctm/assets/94730504/8bdd9c10-3c20-45e7-ad90-5fb2cea570eb">
