### ISSUE TITLE
Card Hover

### ISSUE THREAD

**Issue by iLestar** [sena-proyectos/practicas-ctm#60]
![firefox_hK2YhBi2GY](https://github.com/sena-proyectos/practicas-ctm/assets/71247432/cf59bb6b-24da-42af-8b00-8bfcc44046c4)

**Comment by StivenKN** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ISSUE #60 (Card Hover)](https://trello.com/c/aww5S6gQ/53-issue-60-card-hover)

**Comment by StivenKN** [comment]
#106
