### ISSUE TITLE
Register form use Login route

### ISSUE THREAD

**Issue by StivenKN** [sena-proyectos/practicas-ctm#62]
![imagen](https://github.com/sena-proyectos/practicas-ctm/assets/80909795/6c42d10c-450e-4f71-8b58-f12ac39ce971)

Register doesn't works

**Comment by StivenKN** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ISSUE #62 (Register form use Login route)](https://trello.com/c/vtezfhWq/52-issue-62-register-form-use-login-route)

**Comment by lorenqg** [comment]
<img width="960" alt="image" src="https://github.com/sena-proyectos/practicas-ctm/assets/94730504/767ed8ca-75c3-4cda-b13b-5cdde31fd355">

Se soluciono la ruta que usa el registro en #67
