### ISSUE TITLE
Login Bug

### ISSUE THREAD

**Issue by StivenKN** [sena-proyectos/practicas-ctm#63]
https://github.com/sena-proyectos/practicas-ctm/assets/80909795/4b443af1-694f-45db-b22d-a4b1df63b02c

**Comment by StivenKN** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ISSUE #63 (Login Bug)](https://trello.com/c/EQxc2ek3/51-issue-63-login-bug)

**Comment by lorenqg** [comment]
#67
