### ISSUE TITLE
No hay accesibilidad a la ruta "/fichas"

### ISSUE THREAD

**Issue by StivenKN** [sena-proyectos/practicas-ctm#74]
https://github.com/sena-proyectos/practicas-ctm/assets/80909795/1af44f07-6559-456d-96ad-d1a166381a5d

**Comment by StivenKN** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ISSUE #74 (No hay accesibilidad a la ruta "/fichas")](https://trello.com/c/cDB3E26L/55-issue-74-no-hay-accesibilidad-a-la-ruta-fichas)

**Comment by lorenqg** [comment]
<img width="960" alt="image" src="https://github.com/sena-proyectos/practicas-ctm/assets/94730504/61f3bf94-1338-4cd2-b3b4-29413af723df">

#78
